travis:
  secure:
    BINSTAR_TOKEN: Ko1Wbggj+WQcSTIq5qFr5h2z82KghHeeuQdKqgWUGR2nwh3BvCyVWXshiRPYBWH/khMjbRie4Kz3kdFNS+dvNux1c7dydmupdsEXtVlKhf3pIBY9e2srN0lBbZkZzCo46EagHSJrR0mf0UAURPdHehAF7DNF0va3g8VO2+3mVcNal85Ev2Vej4kKf8yBQ1KZBTa0RAv37U3B1KUj8nSXFPXcv+5e03dSSna7q4csD3615ViEu/bIvjVPbPM61KTO8hKZLUZMpZ/0GMxZxR9ZVhkA/2CQ2p8FYWt7B+lvkOXSPPgvaFP4Nn0Tpklqoo6GLuIC6FjWQQ2Q93Hw7LyMF6J+mu7JC/CyMBMEiWcJb3XHKGiziWak6OlQwWNWw9XnJLMtCOXPCo8moGWG7kUtAMIgwpuakStKjWH367hn9q6jZvKIurl9greFzpO5qh2n109cROI3b/kH2D5teq+24uyB2wqkUSalH9ExMZwsCq6xaHEFL9PoKkFV7ds9ptKRWL1lYpBpN5/0oQw9EwPLcXXrSuDcnObr6tldZZu2X9+H+WIbhRiIUJaqZ2sl7GQj3gB6vWTaqUbbkK4C8ts6Hn2ScmeL/1fwNtwhRozLoU6Li4Vcw06URe22fYYOrzse4HGLyFQ12ZqrdYHdZ6KVVdMOsz6Ptl1ztUehTJgydBM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
