travis:
  secure:
    BINSTAR_TOKEN: TdyZJpGae78IrXHLzkw8/S2emaH+4JWe+ztXWcQPWt+yCpLoyEJ6X4fkM6VRw6iI1e5Bwr41/ENijXj/5UOpMIUYF/sCR6HZi+alCGFU9AbG1OlVwQ7TT2oa6kmQxEBmswcsYriIxcwMCYGfAyhTd6vc8ss1dUt1jCJAA/EIZ990Bh1IgWgsQblZOdzvPz8os0sP1X0w/rTEowla+EHda9YCQKW/nVGVnDKVGthmNpIJgTPJj1kD/kJ9x2gy5Gm4z0PfqCZ07tconyQqufz5169ZqRAVR1x9y3sx57rkJcfYMvBGgBClQa7YzLGnxeEh7DyeWJD0Ot/QP9gUBTAeD+4DLXYb9284PQlDErvinVTB98j5HrxkNnhnkAfQj8jCPb0of6WKJJ42ZVXjVRuiM62ud1236yclafoRy0i/VYRc3NZm1ESfvjJu25ZF6NhkflRBPsFE5rOl03nBDmlzxXGIkt9immD6R1KQ5NfWZab+yAoXlOv16iPVq8Pq77OYFmjn8iW9KuWkqOe4mfDVkTL5uVsg2LvtR97KmE9Z3sXOnbmEP9jpuHrQsdkVg7d0fCEayMEGqnE71Zpy6IvQ1RYBAOvV3AAka9PG5be1LVMuknwSVj6iJLDi1kt5ZbiqeJ1YkqmTr8hNh+JKr4k4VVJHE8HH+8FvODYKnwUqhuw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
