appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: CwiSLk4xHvNIbHYSBOKSCfaaH90mBRYNtBrmJfspxOrsYs5eysmRuAgP4v+bpESRvjHIo85ny8+DWt6kIc3v1YMcBnyNbYLU6EcE2TXZjG3nAEouR+lLYLBvdRGm2yVQHwEFOcXJVHpnMGraCHdAIkr1QnfV31uQa3zqoOzM9IjNUdXb+guOcWbVhAiTVd8lQ5sRW6UlYxTDZX5wWm36e7N8xExYNptQemZQrswI/zbPj9OiWJaSXdY7bs/tyb0VRLN9a+58KyABLfhjMiMkxgQXcYqJ1R/EkcNzNB5qLM0uQefaaOGylBtnN8UQkUBsb11MmxbxJWi4Pv2xwYIRWgzbNMu4NILcXqzPDClQxlaxJzf+1CKCjCtS4ko+bv2+nGF/zX+KgvVj1Yu0rWuUvs0qBjrJP24bvRKBX/hiHTdPW/doD4ZPcwmtLRkEG1K44LtWTULmHNQUypnW/FMMeJBIlcU7saPb8gS4lPPUxJ/WsWCcYG94BJfQUwPCdgHqWCyoSEZiBRLYGLLH7NZeF0f6bXjPwEDtfRNpy3Gx3jiC7XYV/4Crfnn/XRzPvpgBjN6Tx7RXgi58qjkdygu313CzAee2/tiZQdYxPzNQjKxe/3eZO5kFsFY7wPcGK4zrZv4zl012E0sflWkiCx9erchng45Y+R+QonRhk8qSHLM=
conda_forge_output_validation: true
